USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist TEXT NOT NULL,
  name TEXT NOT NULL,
  release_date INT NOT NULL,
  sales FLOAT NOT NULL,
  genre TEXT NOT NULL,
  PRIMARY KEY(id)
);

SHOW TABLES;
DESCRIBE albums;